apiVersion: v1
kind: Service
metadata:
  name: food-ai-app
  namespace: food-ai
spec:
  type: NodePort
  selector:
    app: food-ai-app
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
    nodePort: 30080
