apiVersion: v1
kind: Secret
metadata:
  name: food-ai-secrets
  namespace: food-ai
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "BTSai123"
  DB_OWNER_PASS: "BTSai123"
  DB_READER_PASS: "BTSai123"
  DB_LOADER_PASS: "BTSai123"
  DB_AUTH_PASS: "BTSai123"

  EMAIL_USER: "lanfr1904@outlook.com"

  EMAIL_PASS: "BTSai123"
