#ident "@(#)$Format:LocalFoodAI_lanfr144:settings.yml:%an:%ae:%ad:%cn:%ce:%cd:%H:%D:%N$"
use_default_settings: true

search:
  formats:
    - html
    - json
server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "local_food_ai_secret"
